### ISSUE TITLE
Not working on Elixir 3.2 (Android 13)

### ISSUE THREAD

**Issue by alexchiu100014** [AyraHikari/SamsungMusicPort#5]
Crash after give out the permissions

```
java.lang.NoSuchMethodError: No virtual method getHoverPopupWindow()Landroid/widget/HoverPopupWindow; in class Landroid/view/View; or its super classes (declaration of 'android.view.View' appears in /system/framework/framework.jar!classes3.dex)
	at com.samsung.android.app.music.support.sdl.samsung.widget.HoverPopupWindowSdlCompat.setPopupGravity(HoverPopupWindowSdlCompat.java:1)
	at com.samsung.android.app.music.support.samsung.widget.HoverPopupWindowCompat.setPopupGravity(HoverPopupWindowCompat.java:4)
	at com.samsung.android.app.musiclibrary.ui.framework.hardware.a.b(AirView.java:2)
	at com.samsung.android.app.musiclibrary.ui.util.c.I(DefaultUiUtils.java:2)
	at com.samsung.android.app.musiclibrary.ui.util.c.H(DefaultUiUtils.java:1)
	at com.samsung.android.app.musiclibrary.ktx.view.c.n(ViewExtension.kt:1)
	at com.samsung.android.app.music.list.mymusic.heart.RecommendItem$d.e(RecommendItem.kt:4)
	at com.samsung.android.app.music.list.mymusic.heart.RecommendItem.c(RecommendItem.kt:28)
	at com.samsung.android.app.music.list.mymusic.heart.a.r2(HeartAdapter.kt:1)
	at com.samsung.android.app.music.list.mymusic.heart.a.t1(HeartAdapter.kt:1)
	at com.samsung.android.app.musiclibrary.ui.list.e0.s1(RecyclerCursorAdapter.kt:19)
	at com.samsung.android.app.musiclibrary.ui.list.e0.D(RecyclerCursorAdapter.kt:1)
	at androidx.recyclerview.widget.RecyclerView$t.l(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$j0.I(RecyclerView.java:28)
	at androidx.recyclerview.widget.RecyclerView$j0.p(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$j0.o(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$d.d(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.GridLayoutManager.z2(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.e2(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.f1(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.GridLayoutManager.f1(GridLayoutManager.java:3)
	at androidx.recyclerview.widget.RecyclerView.a1(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.Y0(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at com.samsung.android.app.musiclibrary.ui.widget.OneUiRecyclerView.onLayout(OneUiRecyclerView.kt:1)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:37)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3911)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3298)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8960)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by AyraHikari** [comment]
New build 1.2.1 has been released, can you try it and confirm if it working?

**Comment by alexchiu100014** [comment]
I think my problem is cause by my rom
my extremely old Mi 3 with LineageOS works
Realme GT Master with Elixir 3.2 still not working
I will ask rom maintainer about this problem

`java.lang.NoSuchMethodError: No virtual method getHoverPopupWindow()Landroid/widget/HoverPopupWindow; in class Landroid/view/View; or its super classes (declaration of 'android.view.View' appears in /system/framework/framework.jar!classes3.dex)
 at com.samsung.android.app.music.support.sdl.samsung.widget.HoverPopupWindowSdlCompat.setPopupGravity(HoverPopupWindowSdlCompat.java:1)
 at com.samsung.android.app.music.support.samsung.widget.HoverPopupWindowCompat.setPopupGravity(HoverPopupWindowCompat.java:4)
 at com.samsung.android.app.musiclibrary.ui.framework.hardware.a.b(AirView.java:2)
 at com.samsung.android.app.musiclibrary.ui.util.c.I(DefaultUiUtils.java:2)
 at com.samsung.android.app.musiclibrary.ui.util.c.H(DefaultUiUtils.java:1)
 at com.samsung.android.app.musiclibrary.ktx.view.c.n(ViewExtension.kt:1)
 at com.samsung.android.app.music.list.mymusic.heart.RecommendItem$d.e(RecommendItem.kt:4)
 at com.samsung.android.app.music.list.mymusic.heart.RecommendItem.c(RecommendItem.kt:28)
 at com.samsung.android.app.music.list.mymusic.heart.a.r2(HeartAdapter.kt:1)
 at com.samsung.android.app.music.list.mymusic.heart.a.t1(HeartAdapter.kt:1)
 at com.samsung.android.app.musiclibrary.ui.list.e0.s1(RecyclerCursorAdapter.kt:19)
 at com.samsung.android.app.musiclibrary.ui.list.e0.D(RecyclerCursorAdapter.kt:1)
 at androidx.recyclerview.widget.RecyclerView$t.l(RecyclerView.java:2)
 at androidx.recyclerview.widget.RecyclerView$j0.I(RecyclerView.java:28)
 at androidx.recyclerview.widget.RecyclerView$j0.p(RecyclerView.java:1)
 at androidx.recyclerview.widget.RecyclerView$j0.o(RecyclerView.java:1)
 at androidx.recyclerview.widget.LinearLayoutManager$d.d(LinearLayoutManager.java:3)
 at androidx.recyclerview.widget.GridLayoutManager.z2(GridLayoutManager.java:12)
 at androidx.recyclerview.widget.LinearLayoutManager.e2(LinearLayoutManager.java:9)
 at androidx.recyclerview.widget.LinearLayoutManager.f1(LinearLayoutManager.java:65)
 at androidx.recyclerview.widget.GridLayoutManager.f1(GridLayoutManager.java:3)
 at androidx.recyclerview.widget.RecyclerView.a1(RecyclerView.java:12)
 at androidx.recyclerview.widget.RecyclerView.Y0(RecyclerView.java:15)
 at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
 at com.samsung.android.app.musiclibrary.ui.widget.OneUiRecyclerView.onLayout(OneUiRecyclerView.kt:1)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:37)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
 at android.view.View.layout(View.java:23694)
 at android.view.ViewGroup.layout(ViewGroup.java:6413)
 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3911)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3298)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8960)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
 at android.view.Choreographer.doCallbacks(Choreographer.java:899)
 at android.view.Choreographer.doFrame(Choreographer.java:832)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7898)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

**Comment by alexchiu100014** [comment]
Now I'm on 3.3
but it still not working
looks like my rom delete or not include something that is important to use Samsung Music
